services:
    api01: &api
        build:
            context: .
            dockerfile: Dockerfile
        hostname: api01
        environment:
            - DB_DRIVER=pgsql
            - DB_HOSTNAME=db
            - DB_PORT=5432
            - DB_MAX_POOL_SIZE=15
            - DB_PASSWORD=123
            - DB_USER=admin
            - DATABASE=rinha
            - PORT=3000
        ports:
            - "3001:3000"
        volumes:
            - ./:/var/www
            - /var/www/vendor
        depends_on:
            - db
        deploy:
            resources:
                limits:
                    cpus: "0.30"
                    memory: "75MB"
        restart: on-failure

    api02:
        <<: *api
        hostname: api02
        ports:
            - "3002:3000"

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api01
            - api02
        ports:
            - "9999:9999"
        deploy:
            resources:
                limits:
                    cpus: "0.20"
                    memory: "20MB"

    db:
        image: postgres:latest
        hostname: db
        environment:
            - POSTGRES_PASSWORD=123
            - POSTGRES_USER=admin
            - PGUSER=admin
            - POSTGRES_DB=rinha
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./postgres.conf:/docker-entrypoint-initdb.d/postgres.conf

        command: postgres -c config_file=/docker-entrypoint-initdb.d/postgres.conf
        deploy:
            resources:
                limits:
                    cpus: "0.7"
                    memory: "380MB"

    # pgadmin:
    #   image: dpage/pgadmin4
    #   environment:
    #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    #     - PGADMIN_DEFAULT_PASSWORD=admin
    #     - PGADMIN_LISTEN_PORT=5050
    #   ports:
    #     - "5050:5050"
    #   depends_on:
    #     - db

networks:
    default:
        driver: bridge
        name: rinha-nginx-2024q1
